// <auto-generated />
using System;
using Backpack.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backpack.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250716194008_AddBackupName")]
    partial class AddBackupName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Backpack.Domain.Entity.Backup", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<uint>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Overwrite")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("SourceId");

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("Backpack.Domain.Entity.History", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("Backpack.Domain.Entity.Location", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<uint>("DestinationBackupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("SourceBackupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationBackupId");

                    b.HasIndex("SourceBackupId");

                    b.ToTable("Locations");

                    b.HasDiscriminator<string>("LocationType").HasValue("Location");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backpack.Domain.Entity.Profile", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Backpack.Domain.Entity.Wildcard", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("BackupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BackupId");

                    b.ToTable("Wildcards");
                });

            modelBuilder.Entity("BackupProfile", b =>
                {
                    b.Property<uint>("BackupsId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ProfilesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BackupsId", "ProfilesId");

                    b.HasIndex("ProfilesId");

                    b.ToTable("BackupProfile", (string)null);
                });

            modelBuilder.Entity("Backpack.Domain.Entity.FileLocation", b =>
                {
                    b.HasBaseType("Backpack.Domain.Entity.Location");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("File");
                });

            modelBuilder.Entity("Backpack.Domain.Entity.Backup", b =>
                {
                    b.HasOne("Backpack.Domain.Entity.Location", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backpack.Domain.Entity.Location", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Backpack.Domain.Entity.History", b =>
                {
                    b.HasOne("Backpack.Domain.Entity.Profile", "Profile")
                        .WithMany("Histories")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Backpack.Domain.Entity.Location", b =>
                {
                    b.HasOne("Backpack.Domain.Entity.Backup", "DestinationBackup")
                        .WithMany()
                        .HasForeignKey("DestinationBackupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backpack.Domain.Entity.Backup", "SourceBackup")
                        .WithMany()
                        .HasForeignKey("SourceBackupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationBackup");

                    b.Navigation("SourceBackup");
                });

            modelBuilder.Entity("Backpack.Domain.Entity.Wildcard", b =>
                {
                    b.HasOne("Backpack.Domain.Entity.Backup", "Backup")
                        .WithMany("Wildcards")
                        .HasForeignKey("BackupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Backup");
                });

            modelBuilder.Entity("BackupProfile", b =>
                {
                    b.HasOne("Backpack.Domain.Entity.Backup", null)
                        .WithMany()
                        .HasForeignKey("BackupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backpack.Domain.Entity.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backpack.Domain.Entity.Backup", b =>
                {
                    b.Navigation("Wildcards");
                });

            modelBuilder.Entity("Backpack.Domain.Entity.Profile", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
